---
title: "Nonresponse Rates and Nonresponse Bias"
author: "Shannon Dickson"
date: "`r format(Sys.Date(), '%B %d %Y')`"
output: 
   bookdown::html_document2:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    theme: paper
---

<style type="text/css">
  
body{ /* Normal  */
  font-size: 12px;
  }
td {  /* Table  */
  font-size: 12px;
}
h1.title {
  font-size: 18px;
  color: DarkBlue;
}
h1 { /* Header 1 */
  font-size: 18px;
}
h2 { /* Header 2 */
  font-size: 18px;
}
h3 { /* Header 3 */
  font-size: 18px;
}
</style>

---

```{r}
data
```

```{r setup, echo = FALSE}
# Global settings
library(knitr)
knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE)

hook_output <- knitr::knit_hooks$get("output")

# Truncate output that is too long
knitr::knit_hooks$set(output = function(x, options) {
  if (!is.null(n <- options$out.lines)) {
    x <- xfun::split_lines(x)
    if (length(x) > n) {
      x <- c(head(x, n), "....\n")
    }
    x <- paste(x, collapse = "\n")
  }
  hook_output(x, options)
})
```

```{r}
# Libraries:
library(tidyverse)
library(weights)
library(jtools)
library(ggpubr)
library(ggplot2)
library(qgraph)
# Read data with select variables:
data_clean <- readRDS("data_clean.RDS")
data<-readRDS("nonresponse_database.RDS")
data_clean$meanNRbias <- data$meanNRbias
data_clean$Mode <- data$ModeA
```



```{r}
# Nonresponse rates and non response bias, Groves and new studies
p1<- data_clean %>% 
      ggplot(aes(MN, AbsRelbias, colour = Groves)) +
      geom_jitter(alpha = 0.3) +
      geom_smooth(method = "lm", se = FALSE) +
      scale_colour_manual(values = c("#74A089", "#DC863B"), name = "", labels = c("New studies", "Groves")) +
      labs(x     = "Nonresponse Rate",
           y     = "Absolute Relative Bias (%)") +
           #title = "Figure 1. Relationship between nonresponse rates and absolute bias") +
          # subtitle = "Weighted correlation: 0.235") +
      theme_bw() +
      theme(plot.title = element_text(element_blank()),
            #plot.title = element_text(family = "Palatino", face = "bold", hjust = 0.5),
            axis.title.x = element_text(family = "Palatino", face = "bold"),
            axis.title.y = element_text(family = "Palatino", face = "bold"),
            legend.text = element_text(family = "Palatino"),
            legend.position = "bottom",
            panel.background = element_rect(fill = 'transparent'), 
            plot.background = element_rect(fill = 'transparent', color=NA),
            legend.background = element_rect(fill='transparent'),
            legend.box.background = element_rect(fill='transparent'))

ggsave('plot1.png', p1, bg='transparent')
```

```{r}
# Statistics for plot
data_clean$Yearcent <- data_clean$Year-1980
NR_YR <- lm(MN ~ Yearcent, data=data_clean)
NB_YR <- lm(AbsRelbias ~ Yearcent, data=data_clean)

# Nonresponse rates and non response bias, Groves and new studies
p2<- data_clean %>% 
      ggplot(aes(Year, MN, colour = Groves)) +
      geom_point(alpha = 0.3) +
      geom_smooth(method = "lm", se = FALSE) +
      scale_colour_manual(values = c("#74A089", "#DC863B"),
                          name = "", labels = c("New studies", "Groves")) +
      labs(x     = "Year",
           y     = "Nonresponse Rates") +
           #subtitle = "Yearly increase in NR (%): .486") +
      #annotate(geom="text", x = 2000, y = 95, label="Yearly % increase in NR:",color="black", size = 3)+
      #annotate(geom="text", x = 2013, y = 95, label= round(NR_YR$coefficients[[2]], 3), color = "black", size = 3, family = "Palantino") +
      theme_bw() +
      theme(plot.title = element_text(family = "Palatino", face = "bold", hjust = 0.5),
            axis.title.x = element_text(family = "Palatino", face = "bold"),
            axis.title.y = element_text(family = "Palatino", face = "bold"),
            legend.text = element_text(family = "Palatino"),
            panel.background = element_rect(fill='transparent'), 
            plot.background = element_rect(fill='transparent', color=NA), 
            legend.background = element_rect(fill='transparent'), 
            legend.box.background = element_rect(fill='transparent'))

# Nonresponse rates and non response bias, Groves and new studies
p3<- data_clean %>% 
      ggplot(aes(Year, AbsRelbias, colour = Groves)) +
      geom_point(alpha = 0.3) +
      geom_smooth(method = "lm", se = FALSE) +
      scale_colour_manual(values = c("#74A089", "#DC863B"),
                          name = "", labels = c("New studies", "Groves")) +
      labs(x     = "Year",
           y     = "Absolute Relative Bias (%)") +
           #subtitle = "Yearly increase in bias (%): 0.078") +
      #annotate(geom="text", x = 2000, y = 95, label="Yearly % increase in NR:",color="black", size = 3) +
      #annotate(geom="text", x = 2013, y = 95, label= round(NB_YR$coefficients[[2]], 3), color = "black", size = 3) +
      theme_bw() +
      theme(plot.title = element_text(family = "Palatino", face = "bold", hjust = 0.5),
            axis.title.x = element_text(family = "Palatino", face = "bold"),
            axis.title.y = element_text(family = "Palatino", face = "bold"),
            legend.text = element_text(family = "Palatino"),
            panel.background = element_rect(fill='transparent'), 
            plot.background = element_rect(fill='transparent', color=NA), 
            legend.background = element_rect(fill='transparent'), 
            legend.box.background = element_rect(fill='transparent'))

p4<- ggarrange(p2, p3, nrow = 1, common.legend = TRUE, legend = "bottom") %>% 
               annotate_figure(top = text_grob("Figure 2. Nonresponse rates increasing yet bias stays the same",
                                               #color = "navyblue",
                                               face = "bold",
                                               size = 14,
                                               family = "Palatino"))

ggsave('plot2.png', p2, bg='transparent')
ggsave('plot3.png', p3, bg='transparent')
ggsave('plot4.png', p4, bg='transparent')
```

```{r}
# Between study variation, NR rates and NR bias
p5 <- data_clean %>% 
        ggplot(aes(MN, meanNRbias, colour = Groves, alpha = 0.4, group = Groves, size = SSizeRR)) + 
        geom_point(aes(MN, AbsRelbias), color = "lightgray", alpha = 0.4) + 
        geom_jitter(alpha = 0.8) +
       # geom_smooth(method = 'lm', formula = y ~ x) +
        scale_colour_manual(values = c("#52854C", "#C3D7A4"),
                            name = "", labels = c("New studies", "Groves")) +
        labs(x     = "Nonresponse Rate",
             y     = "Absolute Relative Bias (%)",
             title = "Variation is greatest within studies") +
        theme_bw() +
        theme(legend.position = "none",
              plot.title = element_text(family = "Palatino", face = "bold", hjust = 0.5),
              axis.title.x = element_text(family = "Palatino", face = "bold"),
              axis.title.y = element_text(family = "Palatino", face = "bold"),
              legend.text = element_text(family = "Palatino"),
              panel.background = element_rect(fill='transparent'), 
              plot.background = element_rect(fill='transparent', color=NA), 
              legend.background = element_rect(fill='transparent'), 
              legend.box.background = element_rect(fill='transparent'))

  #annotate(geom="text", x=41, y=80, label="Groves/Peytcheva correlation = ",color="blue", size=7)+
 # annotate(geom="text", x=71, y=80, label= round(cormeanold[[1]],3),color="blue",size=7)+
 # annotate(geom="text", x=41, y=70, label="New data correlation = ",color="black", size=7)+
 # annotate(geom="text", x=63, y=70, label= round(cormeannew[[1]],3),color="black",size=7)

ggsave('plot4.png', p5, bg='transparent')
```

```{r}
# Between study variation, NR rates and NR bias
data_clean %>% 
        ggplot(aes(MN, meanNRbias, colour = Author, alpha = 0.4, group = Author)) + 
        geom_point(aes(MN, AbsRelbias), color = "lightgray", alpha = 0.4) + 
        geom_boxplot(alpha = 0.4) +
        #geom_smooth(method = 'lm', formula = y ~ x) +
       # scale_colour_viridis_d() +
        labs(x     = "Nonresponse Rate",
             y     = "Absolute Relative Bias (%)",
             title = "Variation is greatest within studies") +
        theme_bw() +
        theme(legend.position = "none",
              plot.title = element_text(family = "Palatino", face = "bold", hjust = 0.5),
              axis.title.x = element_text(family = "Palatino", face = "bold"),
              axis.title.y = element_text(family = "Palatino", face = "bold"),
              legend.text = element_text(family = "Palatino"),
              panel.background = element_rect(fill='transparent'), 
              plot.background = element_rect(fill='transparent', color=NA), 
              legend.background = element_rect(fill='transparent'), 
              legend.box.background = element_rect(fill='transparent'))


data_clean %>% 
        ggplot(aes(MN, AbsRelbias, colour = Topic, alpha = 0.4, group = Topic)) + 
       #geom_point(aes(MN, AbsRelbias), color = "lightgray", alpha = 0.4) + 
        geom_boxplot(alpha = 0.4) +
       #geom_smooth(method = 'lm', formula = y ~ x) +
        scale_colour_viridis_d() +
        labs(x     = "Nonresponse Rate",
             y     = "Absolute Relative Bias (%)",
             title = "Variation is greatest within studies") +
        theme_bw() +
        theme(legend.position = "none",
              plot.title = element_text(family = "Palatino", face = "bold", hjust = 0.5),
              axis.title.x = element_text(family = "Palatino", face = "bold"),
              axis.title.y = element_text(family = "Palatino", face = "bold"),
              legend.text = element_text(family = "Palatino"),
              panel.background = element_rect(fill='transparent'), 
              plot.background = element_rect(fill='transparent', color=NA), 
              legend.background = element_rect(fill='transparent'), 
              legend.box.background = element_rect(fill='transparent'))

  #annotate(geom="text", x=41, y=80, label="Groves/Peytcheva correlation = ",color="blue", size=7)+
 # annotate(geom="text", x=71, y=80, label= round(cormeanold[[1]],3),color="blue",size=7)+
 # annotate(geom="text", x=41, y=70, label="New data correlation = ",color="black", size=7)+
 # annotate(geom="text", x=63, y=70, label= round(cormeannew[[1]],3),color="black",size=7)

ggsave('plot5.png', p5, bg='transparent')
```


```{r}
a1<-data_clean %>%
  group_by(Topic) %>%
  summarise(NRm = mean(MN),
            NBm = mean(AbsRelbias)) %>% 
  ggplot(aes(Topic, NBm)) +
  geom_col() +
  theme_apa() +
  coord_flip()

a2<-data_clean %>%
  group_by(Source) %>%
  summarise(NRm = mean(MN),
            NBm = mean(AbsRelbias)) %>% 
  ggplot(aes(Source, NBm)) +
  geom_col() +
  theme_apa() +
  coord_flip()

a3<-data %>%
  group_by(TopicSalien) %>%
  summarise(NRm = mean(MN),
            NBm = mean(AbsRelbias)) %>% 
  ggplot(aes(TopicSalien, NBm)) +
  geom_col() +
  theme_apa() +
  coord_flip()

a4<-data_clean %>%
  group_by(Mode) %>%
  summarise(NRm = mean(MN),
            NBm = mean(AbsRelbias)) %>% 
  ggplot(aes(Mode, NBm)) +
  geom_col() +
  theme_apa() +
  coord_flip()

a5<-data_clean %>%
  group_by(StatsType) %>%
  summarise(NRm = mean(MN),
            NBm = mean(AbsRelbias)) %>% 
  ggplot(aes(StatsType, NBm)) +
  geom_col() +
  theme_apa() +
  coord_flip()

a6<-data_clean %>%
  group_by(Qtype) %>%
  summarise(NRm = mean(MN),
            NBm = mean(AbsRelbias)) %>% 
  ggplot(aes(Qtype, NBm)) +
  geom_col() +
  theme_apa() +
  coord_flip()

ggarrange(a1, a2, a3, a4, a5, a6, ncol = 3, nrow = 3)
```

```{r}
options(scipen = 999)
data_clean %>% 
  select(Topic, Respondents, Nonrespondents) %>% 
  group_by(Topic) %>% 
  summarise("Non-respondents" = mean(Nonrespondents, na.rm = TRUE),
            "Respondents" = mean(Respondents, na.rm = TRUE)) 

data_clean %>% 
  select(TopicSalien, Respondents, Nonrespondents) %>% 
  group_by(TopicSalien) %>% 
  summarise("Non-respondents" = mean(Nonrespondents, na.rm = TRUE),
            "Respondents" = mean(Respondents, na.rm = TRUE)) 

data_clean %>% 
  select(Source, Respondents, Nonrespondents) %>% 
  group_by(Source) %>% 
  summarise("Non-respondents" = mean(Nonrespondents, na.rm = TRUE),
            "Respondents" = mean(Respondents, na.rm = TRUE)) 

data_clean %>% 
  select(Reminder, Respondents, Nonrespondents) %>% 
  group_by(Reminder) %>% 
  summarise("Non-respondents" = mean(Nonrespondents, na.rm = TRUE),
            "Respondents" = mean(Respondents, na.rm = TRUE)) 

data_clean %>% 
  select(StatsType, Respondents, Nonrespondents) %>% 
  group_by(StatsType) %>% 
  summarise("Non-respondents" = mean(Nonrespondents, na.rm = TRUE),
            "Respondents" = mean(Respondents, na.rm = TRUE))
```
```{r}
# Between study variation, NR rates and NR bias
p6 <- data %>% 
      #ggplot(aes(x = MN, y = AbsRelbias, group = Author, colour = Author)) + 
      ggplot(aes(x = MN, y = AbsRelbias)) + 
        geom_point(size = 1.2, alpha = .5, shape = 1, position = "jitter", colour = "grey") +
        geom_smooth(method = lm,
                    se     = FALSE,
                    size   = .8, 
                    alpha  = .8) +
        labs(x = "Nonresponse Rate",
             y = "Absolute Relative Bias (%)") +
        scale_colour_viridis_d() +
        theme_bw() +
        facet_wrap(~StatsType) +
        theme(legend.position = "none",
              panel.background = element_rect(fill='transparent'), 
              plot.background = element_rect(fill='transparent', color=NA))

ggsave('plot5.png', p6, bg='transparent')
```

```{r}
library(qgraph)

# DAG 1
dag1 <-  matrix(c(0, 1, 0, 0, 0, 1, 1,
                  0, 0, 0, 1, 0, 1, 1,
                  0, 0, 0, 0, 0, 1, 1,
                  0, 1, 0, 0, 0, 1, 1,
                  0, 0, 1, 0, 0, 1, 1,
                  0, 0, 0, 0, 0, 0, -1,
                  0, 0, 0, 0, 0, 0, 0), 7, 7, byrow = TRUE)

Labels <- c("Topic", "Saliency", "Mode", "Incentive", "Source", "NR", "Bias")
qgraph(dag1,
       directed = TRUE, 
       layout = "circle",
       nodeNames = Labels,
       title = "Figure 3. Hypothesised causal structure of Nonresponse and Bias")

# DAG 2
dag2 <-  matrix(c(0, 1,  1, 0,  0, 0, 0,  0,  1, 1,
                  0, 0,  0, 1, .5, 0, 0, .5,  1, 1,
                  1, 1,  0, 0,  0, 0, 0,  0,  1, 1,
                  0, 0,  0, 0, .5, 0, 0, .5,  1, 1,
                  0, 1,  1, 0,  0, 0, 0,  0,  1, 1, 
                  0, 0,  0, 0,  0, 0, 0, .5, .5, 1,
                  0, 0,  0, 0,  0, 0, 0,  0,  0, 2,
                  0, 0, .5, 0,  0, 0, 0,  0,  1, 1, 
                  0, 0,  0, 0,  0, 0, 0,  0,  0, 2,
                  0, 0,  0, 0,  0, 0, 0,  0,  0, 0), 10, 10, byrow = TRUE)

Labels = c("Topic", "Saliency", "Relevance", "Mode", "Incentive", "Source", "Statistic", "Question Type", "NR", "Bias")

network_example<- qgraph(dag2,
                   groups = list("Between-Study Characteristics" = 1:6, "Within-Study Characteristics" = 7:8, "Outcomes" = 9:10),
                   nodeNames = Labels,
                   color = c("#DC863B", "#74A089", "#FAEFD1"),
                   directed = FALSE,
                   legend.cex = 0.7,
                   layout = "spring",
                   palette = "pastel",
                   theme = "TeamFortress",
                   bg = "transparent")
                   #filetype = "png",
                   #filename = "../Presentation/images/network_example")
```

```{r}
#layout(t(1:2))
# DAG 1
dag1 <-  matrix(c(0, 0, .7, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 0, -.5, .5,
                  0, 0, 0, 0, -.5,
                  0, 0, 0, 0, 0), 5, 5, byrow = TRUE)

Labels <- c("Face-to-face", "Topic", "Saliency", "NR", "Bias")
qgraph(dag1,
       groups = list("Between-Study Characteristics" = 1:2, "Within-Study Characteristics" = 3, "Outcomes" = 4:5),
       color = c("#DC863B", "#74A089", "#FAEFD1"),
       directed = FALSE, 
       legend.cex = 0.3,
       layout = "spring",
       palette = "pastel",
       theme = "TeamFortress",
      # nodeNames = Labels,
       bg = "transparent",
       filetype = "png",
       filename = "../Presentation/images/rr_Ex1")

# DAG 2
dag2 <-  matrix(c(0, 0, -.5, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 0, .5, 0,
                  0, 0, 0, 0, .5,
                  0, 0, 0, 0, 0), 5, 5, byrow = TRUE)

Labels <- c("Mode", "Topic", "Saliency", "NR", "Bias")
qgraph(dag2,
       groups = list("Between-Study Characteristics" = 1:2, "Within-Study Characteristics" = 3, "Outcomes" = 4:5),
       color = c("#DC863B", "#74A089", "#FAEFD1"),
       directed = FALSE, 
       legend.cex = 0.7,
       layout = "spring",
       palette = "pastel",
       nodeNames = Labels,
       theme = "TeamFortress",
       bg = "transparent",
       filetype = "png",
       filename = "../Presentation/images/rr_Ex2")

```


